services:
  app:
    build: .
    container_name: kpop_crud
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
    environment:
      BD_HOST: ${BD_HOST}
      BD_PORTA: ${BD_PORTA}
      BD_USERNAME: ${BD_USERNAME}
      BD_PASSWORD: ${BD_PASSWORD}
    depends_on:
      banco:
        condition: service_healthy

  banco:
    image: mariadb:10.11
    container_name: kpop_banco
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: ${BD_DATABASE}
      MARIADB_USER: ${BD_USERNAME}
      MARIADB_PASSWORD: ${BD_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - banco_data:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD-SHELL", "healthcheck.sh --connect --innodb_initialized"]
      interval: 5s
      timeout: 5s
      retries: 20

  phpmyadmin:
    image: phpmyadmin:5.2.3-apache
    container_name: kpop_phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: ${BD_HOST}
      PMA_PORT: ${BD_PORTA}
    depends_on:
      banco:
        condition: service_healthy

volumes:
  banco_data: